### PR TITLE
Blooket coin spammer

### PR DESCRIPTION
**Pull request by Giraffey27**
I just tweaked a bit of the code to allow 1500 coins daily instead of, only 500.  same with the XP amount, 800 instead of 300.

### CODE REVIEW

**Comment by Greenlio** [comment]
im going to kill you
YOU CANNOT ADD MORE
SERVERSIDE LIMIT
STOP SUBMITTING PULL REQUESTS
IDIOT CLOWN IDIOT

**Comment by Giraffey27** [comment]
wtf bro. don't call me an idiot just regularly say it

**Comment by CollynGaming** [comment]
bro its server side you cant add more than 500

**Comment by Giraffey27** [comment]
I'm sorry, I didn't know if this is a technical issue or something. Not that experienced with coding. But please, why do you have to call me an idiot clown. I made no conflict to "greenlio", I jus expected that somebody would regularly tell me about it.

**Comment by Giraffey27** [comment]
Don't mean to be rude, but please stop.

**Pull request closed without merging**
