### PR TITLE
Added a note to stop the "jUsT mAkE nUmBeR tO 69696969"

### PR DESCRIPTION
**Pull request by 3kh0**
I added a note to the top of the file so people would stop making pr's like these:

image

Feel free to edit the note @glixzzy :)

### CODE REVIEW

**Comment by glixzzy** [comment]
oops didn't mean to close it

**Comment by 3kh0** [comment]
> oops didn't mean to close it

Thank you! I am glad I could help! :)

**Comment by donaldli2020** [comment]
really annoying hope this could be resolved

**Comment by donaldli2020** [comment]
like 9999999
tokens per day

**Pull request merged**
