### PR TITLE
Update spamOpenBoxes.js

### PR DESCRIPTION
**Pull request by BlooketHeck**
This script works for me consider adding it?

### CODE REVIEW

**Comment by donaldli2020** [comment]
the original works fine

**Comment by BlooketHeck** [comment]
> the original works fine

i works fine in console but my script works with javascript:

**Comment by donaldli2020** [comment]
okay, but ill fix the syntax

**Comment by glixzzy** [comment]
why.

**Comment by donaldli2020** [comment]
ok made pr

**Comment by donaldli2020** [comment]
> > the original works fine
> 
> i works fine in console but my script works with javascript:

yes, doesn't work 4 bookmark

**Comment by donaldli2020** [comment]
> > > the original works fine
> > 
> > 
> > i works fine in console but my script works with javascript:
> 
> yes, doesn't work 4 bookmark

so I made pr

**Pull request closed without merging**
