### PR TITLE
fix for bookmarks

### PR DESCRIPTION
**Pull request by donaldli2020**
there have been many complaints

### CODE REVIEW

**Comment by gimmy74** [comment]
Theres nothing wrong with the bookmarklets dawg

**Comment by glixzzy** [comment]
man stop making useless prs or ill block you

**Comment by donaldli2020** [comment]
this doesn`t work for bookmars

**Comment by coolman3289** [comment]
Yes, the bookmarklet don’t work

**Review by coolman3289 — COMMENTED** [review]
This should fix it

**Comment by donaldli2020** [comment]
use the edited one

**Comment by coolman3289** [comment]
And where is that?

**Comment by coolman3289** [comment]
Can you link?

**Comment by donaldli2020** [comment]
https://github.com/donaldli2020/blooket-hack/blob/a4e4e9a96ace47c42469e512efc6967fc302555d/global/spamOpenBoxes.js

**Comment by coolman3289** [comment]
Is all the code in this fork fixed?

**Comment by coolman3289** [comment]
Yay!

**Pull request merged**
