### PR TITLE
Add blook value calculator

### PR DESCRIPTION
**Pull request by edward-not**
Basically it says the value of the blooks gained from opening the boxes. 

glizz_y I wish to redeem myself for my awful coding :)

### CODE REVIEW

**Comment by edward-not** [comment]
There was issue raised here that basically made me do this    #548

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
bice

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
nice

**Comment by Greenlio** [comment]
holy, nice! I was gonna make it the same way, but this looks great. I haven't tried it, so I have no clue if it works. Other than that, LGTM.

**Comment by Greenlio** [comment]
oh yeah, and I'm assuming all those blook values are correct

**Comment by glixzzy** [comment]
thats nice.

**Comment by Nobody-720** [comment]
How To Use It ????

**Comment by Nobody-720** [comment]
But Can You Add A Little Changes For It 

EXP : **Buys 1 Box Cost 20 Tokens**
        **Gets A Space Ship**
         **So The Profit Is 55 Tokens **
         
EXP : **Buys 1 Box Cost 20 Tokens**
         **Gets A Stars**
         **So The Profit Is -15 Tokens**

**Comment by Nobody-720** [comment]
**So It means Just Minus The Value With The Amount Of Tokens You Spend On Boxes**

**Comment by donaldli2020** [comment]
> But Can You Add A Little Changes For It
> 
> EXP : **Buys 1 Box Cost 20 Tokens** **Gets A Space Ship** **So The Profit Is 55 Tokens **
> 
> EXP : **Buys 1 Box Cost 20 Tokens** **Gets A Stars** **So The Profit Is -15 Tokens**

> **So It means Just Minus The Value With The Amount Of Tokens You Spend On Boxes**

Okay, pull request [#757 net income as well](./757)

**Pull request merged**
