### PR TITLE
Update addTokens.js

### PR DESCRIPTION
**Pull request by hunpace**

### CODE REVIEW

**Comment by GooseterV** [comment]
Not possible

**Comment by hunpace** [comment]
dang alright well hey thanks for letting me know

**Comment by GooseterV** [comment]
Please close this PR (pull request)

**Comment by hunpace** [comment]
hey yeah i will but i wanna ask first can you sell the blocks when doing
get all blocks

**Comment by FallGuysFan1234** [comment]
Sorry @hunpace you cant D:

**Comment by colbymcdaniel** [comment]
um, the get-all blooks are not working for me. any good ideas for me?

**Comment by Piplup7575** [comment]
@colbymcdaniel it only works in a live game (run it to make blooket think you have all blooks possible)
they don't save but you can use it as a troll i guess

**Comment by colbymcdaniel** [comment]
thanks, @Piplup7575

**Comment by ggreeeeekid** [comment]
we shold make a hack to un band pepoel

**Comment by ggreeeeekid** [comment]
i am band

**Comment by ggreeeeekid** [comment]
ok

**Comment by ggreeeeekid** [comment]
ha can you help me with sumpthing I got band and it is a big problem

**Pull request closed without merging**
