### PR TITLE
10000Update addTokens.js

### PR DESCRIPTION
**Pull request by tonyjackso**

### CODE REVIEW

**Comment by gimmy74** [comment]
Lord how many times does someone have to say this YOU CAN'T GO OVER 500 ITS NOT POSSIBLE

**Comment by NeurospawN** [comment]
bruh, blooket has a 500 daily token limit and cannot be exceeded, you cant modify it to give you more than the daily token limit, it isn't possible.

**Comment by tonyjackso** [comment]
oh

**Comment by tonyjackso** [comment]
i see

**Comment by tonyjackso** [comment]
Got it, thanks!

**Pull request closed without merging**
