### PR TITLE
Updated Version

### PR DESCRIPTION
**Pull request by BabyfxY**
Blizzard box is now declared once as 25 coins instead of 25 and 20.

### CODE REVIEW

**Comment by Greenlio** [comment]
Duplicate (but not really) of #512

**Comment by BabyfxY** [comment]
this was made before #512 I'm pretty sure

**Comment by Greenlio** [comment]
yes that is why I said not really

**Comment by 3kh0** [comment]
Hey @BabyfxY , they will merge #512 most likely.

**Comment by glixzzy** [comment]
already done

**Pull request closed without merging**
