### PR TITLE
Update addTokens.js

### PR DESCRIPTION
**Pull request by mrprezz**

### CODE REVIEW

**Comment by Greenlio** [comment]
im going to scream
STOP MAKING ADDTOKENS UPDATE PULL REQUESTS

**Comment by Greenlio** [comment]
> im going to scream STOP MAKING ADDTOKENS UPDATE PULL REQUESTS

UNLESS YOU'RE DOING SOMETHING THATS NOT JUST INCREASING NUMBERS

**Comment by willutgilugpiulg** [comment]
LOL

**Review by willutgilugpiulg — COMMENTED** [review]
this is good idea

**Pull request closed without merging**
