### PR TITLE
Add spooky box and update text

### PR DESCRIPTION
**Pull request by LeaderOfTheEvilFrenchGhostBlook**

### CODE REVIEW

**Comment by Greenlio** [comment]
no

**Comment by Greenlio** [comment]
pls no

**Comment by LeaderOfTheEvilFrenchGhostBlook** [comment]
whyyyyyyyyy

**Comment by GlizxyBoi** [comment]
> pls no

yeah why

**Comment by Greenlio** [comment]
we can just add it back when it's time, it's not a hassle at all lmao
kinda useless in my opinion
time to ping funny collaborators!
@glixzzy @varedz

**Comment by GlizxyBoi** [comment]
ok

**Pull request merged**
