### PR TITLE
Update addTokens.js

### PR DESCRIPTION
**Pull request by Exetion**

### CODE REVIEW

**Comment by 3kh0** [comment]
This PR is useless, please read the note in the file!!!

**Review by 3kh0 — CHANGES_REQUESTED** [review]
This pr does not change anything

**Comment by Exetion** [comment]
[image: Screenshot 2021-11-28 4.52.10 PM.png]

**Comment by Exetion** [comment]
this pr changes your life

**Comment by Exetion** [comment]
[image: breaking-news.png]

**Pull request closed without merging**
