### PR TITLE
addTooManyTokens.js

### PR DESCRIPTION
**Pull request by AAAKrish1010**
Too many tokens to earn

### CODE REVIEW

**Comment by gimmy74** [comment]
i die everytime i see this smh

**Comment by AAAKrish1010** [comment]
oof

**Comment by GooseterV** [comment]
https://github.com/glixzzy/blooket-hack/issues/993
You are unable to add more than 500 tokens a day

**Comment by AAAKrish1010** [comment]
:|

**Comment by AAAKrish1010** [comment]
Blooket gonna go

**Pull request closed without merging**
